image:
  repository: ghcr.io/bento-platform/bento_authorization_service
  tag: "0.12.1"

service:
  port: 5000

env:
  - name: DATABASE_URI
    valueFrom:
      secretKeyRef:
        name: authz-db-app
        key: uri
  - name: INTERNAL_PORT
    value: "5000"
  - name: BENTO_DEBUG
    value: "False"
  - name: OPENID_CONFIG_URL
    value: "https://example.com/realms/bento/.well-known/openid-configuration"
  - name: CORS_ORIGINS
    value: "*"
  - name: SERVICE_URL_BASE_PATH
    value: "/api/authorization"