{{- if not .Values.litestream.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-litestream" (include "litestream-svc.fullname" .) }}
  labels:
    {{- include "litestream-svc.labels" . | nindent 4 }}
type: Opaque
stringData:
  LITESTREAM_ACCESS_KEY_ID: {{ required "set litestream.credentials.accessKeyId or litestream.credentials.existingSecret" .Values.litestream.credentials.accessKeyId | quote }}
  LITESTREAM_SECRET_ACCESS_KEY: {{ required "set litestream.credentials.secretAccessKey or litestream.credentials.existingSecret" .Values.litestream.credentials.secretAccessKey | quote }}
{{- end }}
