apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "litestream-svc.fullname" . }}
  labels:
    {{- include "litestream-svc.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "litestream-svc.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      {{- include "litestream-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "litestream-svc.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "litestream-svc.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-litestream-restore
          image: "{{ .Values.litestream.image.repository }}:{{ .Values.litestream.image.tag }}"
          imagePullPolicy: {{ .Values.litestream.image.pullPolicy }}
          args:
            - restore
            {{- if .Values.litestream.restore.ifDBNotExists }}
            - -if-db-not-exists
            {{- end }}
            {{- if .Values.litestream.restore.ifReplicaExists }}
            - -if-replica-exists
            {{- end }}
            - -config
            - /etc/litestream.yml
            - {{ .Values.sqlite.databasePath }}
          env:
            - name: LITESTREAM_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "litestream-svc.litestreamSecretName" . }}
                  key: LITESTREAM_ACCESS_KEY_ID
            - name: LITESTREAM_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "litestream-svc.litestreamSecretName" . }}
                  key: LITESTREAM_SECRET_ACCESS_KEY
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: litestream-config
              mountPath: /etc/litestream.yml
              subPath: litestream.yml
          {{- with .Values.litestream.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - name: litestream
          image: "{{ .Values.litestream.image.repository }}:{{ .Values.litestream.image.tag }}"
          imagePullPolicy: {{ .Values.litestream.image.pullPolicy }}
          args:
            - replicate
            - -config
            - /etc/litestream.yml
          {{- if .Values.litestream.metrics.enabled }}
          ports:
            - name: ls-metrics
              containerPort: {{ .Values.litestream.metrics.port }}
              protocol: TCP
          {{- end }}
          env:
            - name: LITESTREAM_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "litestream-svc.litestreamSecretName" . }}
                  key: LITESTREAM_ACCESS_KEY_ID
            - name: LITESTREAM_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "litestream-svc.litestreamSecretName" . }}
                  key: LITESTREAM_SECRET_ACCESS_KEY
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: litestream-config
              mountPath: /etc/litestream.yml
              subPath: litestream.yml
          {{- with .Values.litestream.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: litestream-config
          configMap:
            name: {{ printf "%s-litestream" (include "litestream-svc.fullname" .) }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "litestream-svc.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- with .Values.persistence.storageClassName }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
