---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  labels:
    app.kubernetes.io/name: cnpg
    app.kubernetes.io/component: cnpg
    app.kubernetes.io/part-of: infra

spec:
  project: infra
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.26.0

    helm:
      values: |
        installCRDs: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
