---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

# App-of-apps pattern
resources:
  - cert-manager-app.yaml
  - cnpg-app.yaml
  # - envoy-gateway-app.yaml
  - garage-operator-app.yaml
  - keycloak-operator-app.yaml
