image:
  repository: ghcr.io/bento-platform/bento_web
  tag: "7.4.0"

service:
  port: 80

env:
  - name: BENTO_UID
    value: "1000"
  - name: BENTO_CBIOPORTAL_ENABLED
    value: "false"
  - name: BENTO_MONITORING_ENABLED
    value: "false"
  - name: BENTO_URL
    value: "https://portal.bento.k8s.local"
  - name: BENTO_PUBLIC_URL
    value: "https://bento.k8s.local"
  - name: OPENID_CONFIG_URL
    value: "https://auth.bento.k8s.local/realms/bentov2/.well-known/openid-configuration"
  - name: CLIENT_ID
    value: "local_bentov2"

httpRoute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      sectionName: default
      namespace: gateway
  hostnames:
    - portal.bento.k8s.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
