---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageAdminToken
metadata:
  name: garage-admin-token
  namespace: default
spec:
  clusterRef:
    name: garagekubectl apply -f deployment/platform/garage/admin-token-secret.yaml