---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - garage-cluster.yaml
  - drs-bucket.yaml
  - drs-bucket-key.yaml
  - drop-box-bucket.yaml
  - drop-box-bucket-key.yaml
  - http-route.yaml
  - admin-token-secret.yaml