---
apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db-rw.keycloak.svc.cluster.local
    database: keycloak
    usernameSecret:
      name: keycloak-db-app
      key: username
    passwordSecret:
      name: keycloak-db-app
      key: password
  http:
    httpEnabled: true
  proxy:
    headers: xforwarded
  hostname:
    strict: false
  startOptimized: false
  
  # MASTER REALM ADMIN BOOTSTRAP:
  # This manifest will create a temporary admin user for the master realm, with credentials 
  # in the `keycloak-initial-admin` k8s Secret created by the operator.
  # 
  # For prod scenarios, we recommend specifying the master real admin user via `spec.bootstrapAdmin`.
  # See: https://www.keycloak.org/operator/advanced-configuration#_admin_bootstrapping