image:
  repository: ghcr.io/bento-platform/bento_notification_service
  tag: "3.1.17"

service:
  port: 5000

env:
  - name: BENTO_UID
    value: "1000"
  - name: FLASK_DEBUG
    value: "False"
  - name: DATABASE
    value: /notification/data
  - name: REDIS_HOST
    value: valkey.default.svc.cluster.local
  - name: REDIS_PORT
    value: "6379"
  - name: INTERNAL_PORT
    value: "5000"
  - name: BENTO_AUTHZ_ENABLED
    value: "False"
  - name: BENTO_AUTHZ_SERVICE_URL
    value: "http://authz-stateless-svc:5000"
  - name: CORS_ORIGINS
    value: "*"
  - name: FLASK_APP
    value: app