image:
  repository: ghcr.io/bento-platform/bento_notification_service
  tag: "3.1.17"

service:
  port: 5000

livenessProbe:
  httpGet:
    path: /service-info
    port: http
readinessProbe:
  httpGet:
    path: /service-info
    port: http
startupProbe:
  httpGet:
    path: /service-info
    port: http
  failureThreshold: 30
  periodSeconds: 5

persistence:
  enabled: true
  size: 1Gi
  mountPath: /notification/data

env:
  - name: BENTO_UID
    value: "1000"
  - name: FLASK_DEBUG
    value: "False"
  - name: DATABASE
    value: /notification/data
  - name: REDIS_HOST
    value: valkey-primary
  - name: REDIS_PORT
    value: "6379"
  - name: INTERNAL_PORT
    value: "5000"
  - name: BENTO_AUTHZ_ENABLED
    value: "False"
  - name: BENTO_AUTHZ_SERVICE_URL
    value: "http://authz-stateless-svc:5000"
  - name: CORS_ORIGINS
    value: "*"
  - name: FLASK_APP
    value: app