---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  # Allows the toggling of auto-sync on generated Applications
  # while keeping track of SyncOptions like: CreateNamespace and ServerSideApply
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy/automated
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/bento-platform/bento-helm-charts.git
        revision: exp/cilogon-oidc-pkce
        files:
          - path: deployment/services/*/.argocd-app.yaml
  template:
    metadata:
      name: "{{.path.basename}}"

    spec:
      project: "default"

      sources:
        - repoURL: https://github.com/bento-platform/bento-helm-charts.git
          targetRevision: exp/cilogon-oidc-pkce
          ref: values

        - chart: "{{.chart.name}}"
          helm:
            valueFiles:
              - $values/{{.path.path}}/values.yaml
          repoURL: "{{.chart.repoURL}}"
          targetRevision: "{{.chart.version}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "default"

      syncPolicy:
        automated:
          enabled: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
