image:
  repository: ghcr.io/bento-platform/bento_public
  tag: "0.31.0"

service:
  port: 5000

env:
  - name: BENTO_UID
    value: "1000"
  - name: BENTO_PUBLIC_SERVICE_ID
    value: "bentov2-public"
  - name: BENTO_PUBLIC_CLIENT_NAME
    value: "BentoPublicDev"
  - name: BENTO_PUBLIC_PORTAL_URL
    value: "https://portal.bento.k8s.local"
  - name: BENTO_PUBLIC_TRANSLATED
    value: "true"
  - name: BENTO_PUBLIC_SHOW_HEADER_TITLE
    value: "true"
  - name: BENTO_PUBLIC_SHOW_PORTAL_LINK
    value: "true"
  - name: BENTO_PUBLIC_SHOW_SIGN_IN
    value: "true"
  - name: BENTO_PUBLIC_FORCE_CATALOGUE
    value: "false"
  - name: BENTO_PUBLIC_PCGL_MODE
    value: "false"
  - name: BENTO_BEACON_UI_ENABLED
    value: "true"
  - name: BENTO_BEACON_NETWORK_ENABLED
    value: "false"
  - name: BEACON_URL
    value: "https://bento.k8s.local/api/beacon"
  - name: BENTO_PUBLIC_URL
    value: "https://bento.k8s.local"
  - name: BENTO_PUBLIC_PORT
    value: "5000"
  - name: OPENID_CONFIG_URL
    value: "https://test.cilogon.org/.well-known/openid-configuration"
  - name: CLIENT_ID
    value: "cilogon:oa4mp,2012:/client_id/67b21100e8b49e3e3ddfa45bbaeda63a"

httpRoute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      sectionName: root
      namespace: gateway
  hostnames:
    - bento.k8s.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
