---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  # Allows the toggling of auto-sync on generated Applications
  # while keeping track of SyncOptions like: CreateNamespace and ServerSideApply
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy/automated
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/bento-platform/bento-helm-charts.git
        # TODO: set to HEAD before merge
        revision: 21-madr-deployment-structure
        directories:
          - path: deployment/infra/*
  template:
    metadata:
      name: infra-{{.path.basename}}
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/bento-platform/bento-helm-charts.git
        # TODO: set to HEAD before merge
        targetRevision: 21-madr-deployment-structure
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        # e.g. for dir "infra/cert-manager", the resources will be deployed in
        # namespace "cert-manager"
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          enabled: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
