---
image:
  repository: ghcr.io/bento-platform/bento_authorization_service
  tag: "0.12.1"

service:
  port: 5000

env:
  - name: DATABASE_URI
    valueFrom:
      secretKeyRef:
        name: authz-db-app
        key: uri
  - name: INTERNAL_PORT
    value: "5000"
  - name: BENTO_DEBUG
    value: "False"
  - name: OPENID_CONFIG_URL
    value: "https://auth.bento.k8s.local/realms/bentov2/.well-known/openid-configuration"
  - name: CORS_ORIGINS
    value: "*"
  - name: SERVICE_URL_BASE_PATH
    value: "/"

httpRoute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      sectionName: default
      namespace: gateway
  hostnames:
    - authz.bento.k8s.local
# Leave backendRefs to be templated by the Helm Chart
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /